defaults: &defaults
  docker:
    - image: circleci/node:10.13
  working_directory: ~/repo
  
version: 2.1
jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          #- v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          #- v1-dependencies-
          - npm-cache
      - run:
          name: Install Dependencies 
          command: npm ci
      - save_cache:
          paths:
          - ~/.npm
          key: npm-cache
          #  - node_modules
          #key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/
          paths: 
            - repo
            - .ssh/known_hosts

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: 
          name: Lint Code
          command: npm run lint  

  test:
    <<: *defaults
    steps:
    - attach_workspace:
        at: ~/
    - run: 
        name: Run Tests 
        command: npm run test
   # - store_artifacts:
   #     path: ./test-results/coverage

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: 
          name: Build Application
          command: npm run build
      - persist_to_workspace:
          root: ~/
          paths: 
            - repo/dist

  checksize:
    <<: *defaults
    # size limit > 1.0 runs puppeteer which requries having an image with chrome
    #  docker:
    #    - image: circleci/node:10.15-browsers-legacy
    #  working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: Check Bundle Size
          command: npm run size 

  e2e:
    docker:
      - image: circleci/node:10.15-browsers-legacy
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/
      - run: 
          name: run local server
          background: true
          command: npm run start:prod 
      - run:
          name: run e2e tests
          command: npm run e2e
      - store_artifacts:
          path: ~/repo/test-results/e2e

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - add_ssh_keys
      - run: 
          name: Set git user and email
          command: |
              git config user.name $GIT_NAME
              git config user.email $GIT_EMAIL
      - run: 
          name: Deploy to GitHub pages
          command: NODE_DEBUG=gh-pages npm run deploy

workflows:
  version: 2
  lint-test-bundle-deploy:
    jobs:
      - prepare
      - lint:
          requires:
            - prepare
      - test:
          requires:
            - prepare
      - build:
          requires:
            - prepare
      - checksize:
          requires:
            - build
      - e2e:
          requires:
            - build
      - deploy:
          requires:
            - test
            - lint
            - build
            - checksize
            - e2e
          # filters:
          #   branches:
          #     only: master