version: 2
jobs:
  pre-build:
    docker:
      - image: circleci/node:10.13

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Install dependencies 
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/
          paths: 
            - repo
    
  build:
    docker:
      - image: circleci/node:10.13
    working_directory: ~/repo
    steps:
      - attach_workspace:
        - at: ~/
      - run: 
        name: Build application
        command: npm run build
      - run:
        name: check size
        command: echo 'checksize'
    
  test:
    docker:
      - image: circleci/node:10.13
    working_directory: ~/repo
    steps:
      - attach_workspace:
        - at: ~/
    - run: 
        name: Lint code
        command: npm run lint
    - run: 
        name: Run tests 
        command: npm test

  lint:
    docker:
      - image: circleci/node:10.13
    working_directory: ~/repo
    steps:
      - attach_workspace:
        - at: ~/
      - run: 
        name: Lint code
        command: npm run lint

workflow:
  version: 2
  build-lint-test
    jobs:
      - pre-build
      - build
          requires:
            - pre-build
      - lint
         requires:
            - pre-build
      - test
          requires:
            - pre-build