defaults: &defaults
  docker:
    - image: circleci/node:10.13
  working_directory: ~/repo
  
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Install Dependencies 
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/
          paths: 
            - repo

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: 
          name: Lint Code
          command: npm run lint  

  test:
    <<: *defaults
    steps:
    - attach_workspace:
        at: ~/
    - run: 
        name: Run Tests 
        command: npm run test
   # - store_artifacts:
   #     path: ./coverage
   #     destinate: coverage

  bundle:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: 
          name: Build Application
          command: npm run build
      - run:
          name: Check Bundle Size
          command: npm run size

  e2e:
    docker:
      - image: circleci/node:10.15-browsers-legacy
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/
      - run: 
          name: run local server
          background: true
          command: npm run start:prod 
      - run:
          name: run e2e tests
          command: npm run e2e

workflows:
  version: 2
  lint-test-bundle:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
      - bundle:
          requires:
            - build
      - e2e:
          requires:
            - bundle